version: "3.9"

services:
  frontend-nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - xball
    command: npm run start

networks:
  xball:
    driver: bridge
    external: true
